### PR TITLE
V1.3.1 fix annotation profile

### PR DESCRIPTION
**Pull request by kvb2univpitt**

### CODE REVIEW

**Comment by kvb2univpitt** [comment]
Needs more work to remove annotations.

**Comment by yuanzhou** [comment]
@kvb2univpitt you can still reopen this PR, and commit all of your changes to your v1.3.1-fix-annotation-profile. Then your new commits will be appended in this PR. You don't have to close it.

**Comment by kvb2univpitt** [comment]
@yuanzhou I reopened this issue and made additional changes.  Can you please review and merge it now?

**Comment by yuanzhou** [comment]
@kvb2univpitt I tested the new version and deployed on AWS with the annotation profile turned off, no longer see those annotation errors after registering a new user. Do we also need to test to see if everything works fine with annotation profile turned on? I can't test the annotation profile on AWS though. If no need then I'm happy to merge this PR. Thanks!

**Comment by yuanzhou** [comment]
I also tested in both Shiro and Auth0 login mode, didn't see any other issues.

**Comment by yuanzhou** [comment]
@kvb2univpitt I'll let you delete the merged branch in case you are still working on something using it.

**Pull request merged**
